export type Chapter = { id: string; roman: string; label: string; title: string; description: string; cover: string };
export type Stop = { id: string; chapter: number; title: string; emphasis: string; kicker: string; paragraphs: string[]; detail: string; plates: string[]; next: string };
export const chapters: Chapter[] = [
  {id:'world',roman:'I',label:'The world',title:'The known world',description:'A northern crown. A southern forest. A continent full of unfinished stories.',cover:'01'},
  {id:'ebon',roman:'II',label:'Ebon Vale',title:'A home worth defending',description:'Begin where the forest meets the sea, in the small town that holds the campaign’s heart.',cover:'06'},
  {id:'forest',roman:'III',label:'Mystarion',title:'Into the living forest',description:'Follow the roots of the Heartwood and the blue flowers beside the Font.',cover:'07'},
  {id:'citidaea',roman:'IV',label:'The Citidaea',title:'The city of nine Seals',description:'Poured sandstone, captured starlight, and an empire’s careful grip.',cover:'12'},
  {id:'isles',roman:'V',label:'The sky isles',title:'Above the harvest',description:'The Mad Pirate Queen rules a kingdom held aloft by ancient machines.',cover:'16'},
  {id:'elements',roman:'VI',label:'Fire & tide',title:'Where spirits still endure',description:'A forge beneath a bare mountain. A coastline waiting to be healed.',cover:'18'},
  {id:'veil',roman:'VII',label:'Beyond the veil',title:'Where the stars remember',description:'Enter Nitriti’s temple, unfold the mirrored sky, and cross into the Near-Spirit.',cover:'20'},
  {id:'uncharted',roman:'VIII',label:'Uncharted',title:'At the edge of the ink',description:'A kingdom rises toward the moon. Beyond familiar shores, the atlas opens again.',cover:'28'},
];
export const stops: Stop[] = [
  {id:'valisar',chapter:0,title:'A world waiting',emphasis:'to be remembered.',kicker:'THE KNOWN WORLD',paragraphs:['Trace the northern mountain spine west into the Fuhran Desert, then follow the continent south through Mystarion to Ebon Vale.','The Sakazarac Empire claims the land. Spirits, forgotten histories, and the source of magic itself run deeper than its borders.'],detail:'Your journey begins on the same continental outline as Cody’s early world map.',plates:['01','02'],next:'Follow the southern road'},
  {id:'southern-reach',chapter:1,title:'At the edge',emphasis:'of the forest.',kicker:'THE SOUTHERN REACH',paragraphs:['The Shattered Ridge curls around Ebon Forest in a great horseshoe. Black-barked trees fill its sheltered interior, and the Obsidian Sea opens to the east.','Here, at the southern coast, the road arrives in Ebon Vale. Beyond the ridge to the north lies Mystarion.'],detail:'The mountain arc follows the original regional map embedded in the campaign notes.',plates:['03','04'],next:'Enter Ebon Vale'},
  {id:'ebon-vale',chapter:1,title:'A home worth',emphasis:'defending.',kicker:'EBON VALE',paragraphs:['Braxon’s forge warms the square. Enchanted furniture waits at Charmed Chaises, and the Dancing Pig offers a place to gather. The Lamn family lives close by.','At Brother Soren’s wooden chapel, dwarven refugees from Thunderforge find shelter. A small town becomes the meeting place of much larger stories.'],detail:'Look for the forge, the furniture shop, the refugee carts, and the chapel’s wind chimes.',plates:['05','06'],next:'Watch the Solar Wind arrive'},
  {id:'solar-wind',chapter:1,title:'The light of',emphasis:'the Empire.',kicker:'THE FESTIVAL OF RADIANT DAWN',paragraphs:['The Solar Wind arrives like a cathedral lifted into the sky: silverwood, gold, stained-glass towers, and a sun-winged prow. Four crimson-and-gold escorts surround it.','Golden bridges descend toward the town. Elaina Masque’s entrance turns the Festival of Radiant Dawn into a spectacle of imperial power.'],detail:'A later moment in Ebon Vale’s story, after the town has already suffered the fires.',plates:['23'],next:'Cross the Shattered Ridge'},
  {id:'mystarion',chapter:2,title:'The forest',emphasis:'has many voices.',kicker:'MYSTARION',paragraphs:['Mystarion holds many kinds of forest, from dense jungle to dry woodland. Its paths lead toward Dagan’s Grove, the eastern lake, and the far northwestern Verdant Deeps.','Cernis, Taranis, and Grimore inhabit the margins of this map as the powers that shape the wood. Follow their gaze toward the Heartwood.'],detail:'Cernis bears an antlered, rabbit-like face; Taranis appears as the Laughing Crow.',plates:['07'],next:'Find the Heartwood'},
  {id:'dagans-grove',chapter:2,title:'A city around',emphasis:'a living heart.',kicker:'DAGAN’S GROVE',paragraphs:['The Heartwood’s trunk spans a hundred feet. Its base is solid tree; above it, the Cord of Elders occupies the second and third levels. Streets, markets, and neighborhoods spiral outward.','Find the Sylvan Archive, the Whispering Leaf, and the Starlit Stag. The Guarded Gardens belongs to Kaelen Goldeneye, whose sanctuary holds neutral ground.'],detail:'Lake Mirrara appears at the eastern edge as a compressed glimpse of the surrounding region.',plates:['08','09'],next:'Follow the sapphire flowers'},
  {id:'lake-mirrara',chapter:2,title:'Blue flowers.',emphasis:'Ancient power.',kicker:'LAKE MIRRARA',paragraphs:['Due east of Dagan’s Grove, a shallow lake surrounds a single island. A giant stone arch rises at its center, beside the powerful leyline called the Font.','The water is only four to five feet deep. Geometrically perfect sapphire crocuses grow here, flowers valuable enough to be drawn into the Citidaea’s spirit-containment research.'],detail:'In the pixel map, corruption bruises the northern shore while a cleansing arc crosses the south.',plates:['10','11'],next:'Meet Que’Rubra'},
  {id:'querubra',chapter:2,title:'Children',emphasis:'in the boughs.',kicker:'QUE’RUBRA, FIN & BIN',paragraphs:['An ancient oak spirit stands among the trees, her bark written with runes and her hair alive with leaves. Que’Rubra carries the Moonlit Thorn and serves as Nitriti’s lieutenant.','Here she holds Fin and Bin, her joyful twig children, in a quiet moment before her capture.'],detail:'A peaceful portrait preserves the family before the campaign’s darker turn.',plates:['25'],next:'Travel west to the Citidaea'},
  {id:'citidaea',chapter:3,title:'A city poured',emphasis:'from stone.',kicker:'THE CITIDAEA',paragraphs:['Ocean to the west. Red desert to the east. Inside a coastal canyon, sandstone towers follow the leylines, connected by glass-and-brass bridges and floating platforms.','The nine Seals stand in an irregular arrangement. Each school keeps its own domain; the Ninth answers directly to the Crown.'],detail:'Find all nine numbered towers, the beehive-shaped Libra Stellae, and the Mirrored Dome of the Third Seal.',plates:['12','13'],next:'Look into the city’s past'},
  {id:'ninth-seal',chapter:3,title:'Before the',emphasis:'Ninth Seal.',kicker:'TWO MEMORIES OF ONE CITY',paragraphs:['A starlight recording remembers a greener northern canyon and the colors of eight Seals. Another shows damaged towers, cold crystal light, and the city’s incorporation into the Empire.','The Ninth Seal turns conquest into a permanent presence. These two views share an imagined city plan, seen on either side of that change.'],detail:'The historical reconstruction follows the two recordings encountered in Session 36.',plates:['14'],next:'Descend into Libra Stellae'},
  {id:'libra-stellae',chapter:3,title:'What the',emphasis:'stars remember.',kicker:'LIBRA STELLAE',paragraphs:['A spiraling ramp descends into a deep circular chamber. Thousands of crystal alcoves line the walls, and researchers move between the tiers on floating platforms.','Knowledge is held in infused starlight and read by touch. Among the great histories, Vespine has a favorite crystal: a memory of frogs.'],detail:'Look closely at the crystal in the foreground. Even the smallest remembered life has a place here.',plates:['24'],next:'Rise above the Sweeping Plains'},
  {id:'tradewind-isles',chapter:4,title:'A kingdom',emphasis:'above the harvest.',kicker:'THE TRADEWIND ISLES',paragraphs:['Fifteen hundred feet above the Sweeping Plains, ancient anti-gravity machines hold Blackwake’s islands in the sky. The Mad Pirate Queen rules from the Coral Throne.','Far below, the Empire’s breadbasket stretches in fields and farms. To the southeast, the long scar of a fallen island remembers the Queen’s power.'],detail:'The crashed island was a mile long. It fell seven or eight years before the campaign conversation.',plates:['15','16'],next:'Seek the mountain forge'},
  {id:'thunderforge',chapter:5,title:'The fire',emphasis:'beneath the mountain.',kicker:'MOUNT KAJA & THUNDERFORGE',paragraphs:['Thunderforge, capital of Serapheld, lies within and beneath Mount Kaja, tallest of the Echowraith Peaks. Deep halls descend toward the forgefire.','Kojin’s once-dutiful flame now rages. The peak stands largely bare, while a crystal remembers the mountain under snow. Displaced dwarves carry their traditions south to Ebon Vale.'],detail:'The small snowy inset is a memory of the mountain’s earlier appearance.',plates:['18'],next:'Follow the eastern waters'},
  {id:'zalian-coast',chapter:5,title:'Where the',emphasis:'water bruises.',kicker:'THE ZALIAN COAST',paragraphs:['Zalia’s ports, fishers, and navy depend on the ocean spirits. Along the eastern coast, the Ghostly Marshes and an unnatural rot make that dependence painfully clear.','Marin asks Daxon to cleanse these waters. Beneath them lies another history: Serratta, the deep current, and the Sunken Empire.'],detail:'The unnamed harbors and submerged ruins are visual proposals drawn around the coast’s established lore.',plates:['17'],next:'Answer Marin’s call'},
  {id:'marin',chapter:5,title:'A willing',emphasis:'blade.',kicker:'MARIN & TIDECALLER',paragraphs:['Marin takes the form of a woman of clear water, carrying a long spear. Daxon swears to cleanse the Zalian Coast, and Tidecaller’s crossguard rises like a cresting wave.','A spirit-forged blade is a partner to its wielder. This image holds the promise of that bond against the damaged shore.'],detail:'The oath becomes a woodblock sea: moonlight, indigo water, and a blade shaped by a willing spirit.',plates:['26'],next:'Enter Nitriti’s temple'},
  {id:'nitriti',chapter:6,title:'A cathedral',emphasis:'of stars.',kicker:'THE TEMPLE OF NITRITI',paragraphs:['A statue waits for its crown, cloak, and scepter. Beyond the puzzle lie circular stone doors, hidden scripts, a ritual sanctuary, and a secret obsidian observatory.','Nitriti appears through darkness and mist, surrounded by white porcelain masks. This map remembers the temple before its collapse.'],detail:'Follow the numbered chambers to the observatory and its orrery. The room connections are an illustrated reconstruction.',plates:['19'],next:'Unfold the mirrored sky'},
  {id:'mirrored-sky',chapter:6,title:'Three realms.',emphasis:'One mirror.',kicker:'LIRIELLE’S STAR MAP',paragraphs:['Lirielle’s map unfolds across three levels: the surface chart, the Mirrored Sky, and the Near-Spirit. Activated gates connect Ebon Vale, Nitriti’s temple, and Lake Mirrara.','A misplaced star transforms the Weaver into the Deceiver. In this sky, stars brighten with the full moon and dim with the new.'],detail:'The constellation drawings are interpretations. The map’s layers, gates, and unusual moonlight come from the campaign.',plates:['20'],next:'Cross into the Near-Spirit'},
  {id:'roothold',chapter:6,title:'Roads',emphasis:'between worlds.',kicker:'THE ROOTHOLD',paragraphs:['Deep in the Verdant Deeps, northwest of Dagan’s Grove, a portal leads into the Near-Spirit. The Star Map helps reality remember the way.','Althea and Caelum lead the Roothold resistance alongside the great spirits. Roots and pathways become the language of a place beyond ordinary geography.'],detail:'Read the paths symbolically. This woven map gives the resistance a visual home without claiming measured terrain.',plates:['22'],next:'Follow the turning gears'},
  {id:'clock-angel',chapter:6,title:'The eye',emphasis:'behind the clock.',kicker:'AN UNANSWERED VISION',paragraphs:['An enormous unblinking eye turns within wings, rings, and clockwork gears. This is the shape Luigi’s mind gives to his patron.','The image holds its gaze. What watches through it, and why it has turned toward him, remains beyond the edge of the painting.'],detail:'A mortal vision, rendered in fragments. The symbols offer questions; their meaning stays veiled.',plates:['27'],next:'Leave the familiar world'},
  {id:'sunken-kingdom',chapter:7,title:'It happened',emphasis:'on a Tuesday.',kicker:'THE NOT-SO-SUNKEN KINGDOM',paragraphs:['At Tidebreaker Forge in Shimmoth, canal workers investigate the Bossington Ark. Gravity begins to misbehave. A moon appears just above the town.','Then the kingdom is torn upward from the earth. A one-shot becomes a city suspended between the sea and an impossible sky.'],detail:'This chapter preserves the one-shot as its own event, without assigning it a date in the main campaign.',plates:['21'],next:'Sail beyond Valisar'},
  {id:'beyond-valisar',chapter:7,title:'Where the ink',emphasis:'falls silent.',kicker:'THE UNWRITTEN SHORES',paragraphs:['A coastline trails into mist. A distant shape might be a tower, or a mountain. The names have worn away.','Valisar remains familiar at the center. Around it, the page holds only fragments of whatever waits beyond the known sea.'],detail:'An imagined chart of uncertain shores. Follow its traces as possibilities, leaving the blank spaces open.',plates:['28'],next:'Return to the first page'},
];
export const plateLabels: Record<string,string> = {
  '01':'Ink & parchment','02':'16-bit overworld','03':'16-bit region','04':'Traveller’s ink','05':'16-bit village','06':'Watercolor village',
  '07':'Forest woodcut','08':'16-bit city','09':'Painted canopy','10':'16-bit encounter','11':'Botanical survey','12':'Architectural ink',
  '13':'16-bit city','14':'Before & after','15':'Sky chart','16':'16-bit sky isles','17':'Nautical engraving','18':'Mountain cutaway',
  '19':'Temple floor plan','20':'Celestial chart','21':'Kingdom cutaway','22':'Woven spirit map','23':'Imperial arrival','24':'Crystal library',
  '25':'Folktale watercolor','26':'Moonlit woodblock','27':'Celestial vision','28':'Faded fragments',
};
export const worldPins=[
  {label:'Ebon Vale',x:54,y:94,stop:'ebon-vale'},
  {label:'Mystarion',x:46,y:65,stop:'mystarion'},
  {label:'The Citidaea',x:20,y:30,stop:'citidaea'},
  {label:'Tradewind Isles',x:48,y:24,stop:'tradewind-isles'},
  {label:'Thunderforge',x:63,y:16,stop:'thunderforge'},
  {label:'Zalian Coast',x:82,y:31,stop:'zalian-coast'},
];
